apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: ip-publica
  namespace: metallb-system
spec:
  addresses:
  - 195.248.231.236/32
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: l2-config
  namespace: metallb-system
spec:
  ipAddressPools:
  - ip-publica