apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: glpi-web
  namespace: monitoring
  labels:
    team: frontend
spec:
  selector:
    matchLabels:
      app: glpi
  endpoints:
  - port: websecure
